name: Make a release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setting release type
        run: |
          name='${{ github.event.pull_request.head.ref }}'
          if [[ $name == "epic*" ]] ;
          then
                  echo "RELEASE_TYPE=major" >> $GITHUB_ENV
          elif [[ $name == "feature*" ]] ;
          then
                  echo "RELEASE_TYPE=minor" >> $GITHUB_ENV
          else
                  echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
          fi
        shell: bash
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          default_bump: ${{ env.RELEASE_TYPE }}
      - name: Echo steps
        run: |
          echo '${{ toJSON(steps) }}'
        shell: bash
      - name: Create Release
        run: |
          gh release create ${{ steps.tag_version.outputs.new_tag}} <<< ""
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash
